// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package precisely.demo;

// import org.testng.annotations.*;

// import precisely.demo.App;

// import static org.testng.Assert.*;

// public class AppTest {
//     @Test public void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//     }
// }
